# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=200, verbose_name='\u5b66\u53f7')),
                ('name', models.CharField(max_length=200, verbose_name='\u59d3\u540d')),
                ('class_num', models.CharField(max_length=200, verbose_name='\u73ed\u7ea7')),
                ('major', models.CharField(max_length=200, verbose_name='\u4e13\u4e1a')),
                ('c_name', models.CharField(max_length=200, verbose_name='\u8bfe\u7a0b\u540d')),
                ('term', models.CharField(max_length=200, verbose_name='\u5f00\u8bfe\u5b66\u671f')),
                ('c_type', models.CharField(max_length=200, verbose_name='\u8bfe\u7a0b\u6027\u8d28')),
                ('score', models.CharField(max_length=200, verbose_name='\u6210\u7ee9')),
                ('credit', models.CharField(max_length=200, verbose_name='\u5b66\u5206')),
                ('properties', models.CharField(max_length=200, verbose_name='\u8003\u8bd5\u6027\u8d28')),
            ],
            options={
                'verbose_name': '\u5b66\u751f\u6210\u7ee9',
                'verbose_name_plural': '\u5b66\u751f\u6210\u7ee9',
            },
        ),
    ]
